mdapi_output_dir/objects/Corpus__c.object
<CustomObject>
    <label>Corpus</label>
    <nameField>
        <label>Corpus Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corpuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi_output_dir/objects/HHD_Disk__c.object
<CustomObject>
    <label>HHD Disk</label>
    <nameField>
        <label>HHD Disk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HHD Disks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Buffer_capacity__c</fullName>
        <label>Buffer capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Spindle_rotation_speed__c</fullName>
        <label>Spindle rotation speed</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Storage_Capacity__c</fullName>
        <label>Storage Capacity</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inner</fullName>
                </value>
                <value>
                    <fullName>Outer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi_output_dir/objects/Motherboard__c.object
<CustomObject>
    <label>Motherboard</label>
    <nameField>
        <label>Motherboard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Motherboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Formfactor__c</fullName>
        <label>Formfactor</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>M2__c</fullName>
        <label>M2</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Memory_Frequency__c</fullName>
        <label>Maximum Memory Frequency</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Socket__c</fullName>
        <label>Socket</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi_output_dir/objects/Power_supply__c.object
<CustomObject>
    <label>Power supply</label>
    <nameField>
        <label>Power Supply Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Power supplies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cooling_system__c</fullName>
        <label>Cooling system</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inner</fullName>
                </value>
                <value>
                    <fullName>Outer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Formfactor__c</fullName>
        <label>Formfactor</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maximum_noise_level__c</fullName>
        <label>Maximum noise level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_power_connectors__c</fullName>
        <label>Number of  power connectors</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Power__c</fullName>
        <label>Power</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

mdapi_output_dir/objects/Processor__c.object
<CustomObject>
    <label>Processor</label>
    <nameField>
        <label>Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Clock_speed__c</fullName>
        <label>Clock speed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Intel</fullName>
                </value>
                <value>
                    <fullName>AMD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Generation__c</fullName>
        <label>Generation</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_cores__c</fullName>
        <label>Number of cores</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_threads__c</fullName>
        <label>Number of threads</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Socket__c</fullName>
        <label>Socket</label>
        <length>8</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi_output_dir/objects/RAM__c.object
<CustomObject>
    <label>RAM</label>
    <nameField>
        <label>RAM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RAM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Memory_capacity__c</fullName>
        <label>Memory capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Memory_Clock__c</fullName>
        <label>Memory Clock</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_slats__c</fullName>
        <label>Number of slats</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type_of_Memory__c</fullName>
        <label>Type of Memory</label>
        <length>10</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi_output_dir/objects/Sound_Card__c.object
<CustomObject>
    <label>Sound Card</label>
    <nameField>
        <label>Sound Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sound Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Channels__c</fullName>
        <label>Channels</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Color__c</fullName>
        <label>Color</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connection_interface__c</fullName>
        <label>Connection interface</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PCI</fullName>
                </value>
                <value>
                    <fullName>PCIe</fullName>
                </value>
                <value>
                    <fullName>USB 2.0</fullName>
                </value>
                <value>
                    <fullName>mini-Jack (3.5 мм)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inner Card</fullName>
                </value>
                <value>
                    <fullName>Outer Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi_output_dir/objects/SSD_Disk__c.object
<CustomObject>
    <label>SSD Disk</label>
    <nameField>
        <label>SSD Disk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSD Disks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connection_interface__c</fullName>
        <label>Connection interface</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Formfactor__c</fullName>
        <label>Formfactor</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inner</fullName>
                </value>
                <value>
                    <fullName>Outer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi_output_dir/objects/Video_Card__c.object
<CustomObject>
    <label>Video Card</label>
    <nameField>
        <label>Video Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Video Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AMD</fullName>
                </value>
                <value>
                    <fullName>nVidia</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Connectors__c</fullName>
        <label>Connectors</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interface__c</fullName>
        <label>Interface</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Memory_bus_bit_depth__c</fullName>
        <label>Memory bus bit depth</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Memory_capacity__c</fullName>
        <label>Memory capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type_of_Memory__c</fullName>
        <label>Type of Memory</label>
        <length>10</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi_output_dir/classes/MainPage.cls
public without sharing class MainPage {
    public MainPage() {

    }
    @AuraEnabled
    public static List<String> GetProcessorOptions(){
        List<String> so = new List<String>();
        so.add('none');
        for(Schema.PicklistEntry ple:  Processor__c.Company__c.getDescribe().getPicklistValues()){
            so.add(ple.getValue());
        }
        return so;
    }
    @AuraEnabled
    public static List<String> GetPowerOptions(){
        List<String> so = new List<String>();
        so.add('none');
        for(Schema.PicklistEntry ple:  Power_supply__c.Cooling_system__c.getDescribe().getPicklistValues()){
            so.add(ple.getValue());
        }
        return so;
    }
    @AuraEnabled
    public static List<String> GetHHDOptions(){
        List<String> so = new List<String>();
        so.add('none');
        for(Schema.PicklistEntry ple:  HHD_Disk__c.Type__c.getDescribe().getPicklistValues()){
            so.add(ple.getValue());
        }
        return so;
    }
    @AuraEnabled
    public static List<String> GetSSDOptions(){
        List<String> so = new List<String>();
        so.add('none');
        for(Schema.PicklistEntry ple:  SSD_Disk__c.Type__c.getDescribe().getPicklistValues()){
            so.add(ple.getValue());
        }
        return so;
    }
    @AuraEnabled
    public static List<String> GetVideoOptions(){
        List<String> so = new List<String>();
        so.add('none');
        for(Schema.PicklistEntry ple:  Video_Card__c.Company__c.getDescribe().getPicklistValues()){
            so.add(ple.getValue());
        }
        return so;
    }
    @AuraEnabled
    public static List<String> GetSoundOptions(){
        List<String> so = new List<String>();
        so.add('none');
        for(Schema.PicklistEntry ple:  Sound_Card__c.Connection_interface__c.getDescribe().getPicklistValues()){
            so.add(ple.getValue());
        }
        return so;
    }
    @AuraEnabled
    public static List<String> GetSoundTypeOptions(){
        List<String> so = new List<String>();
        so.add('none');
        for(Schema.PicklistEntry ple:  Sound_Card__c.Type__c.getDescribe().getPicklistValues()){
            so.add(ple.getValue());
        }
        return so;
    }
    @AuraEnabled
    public static List<Processor__c> getProcess(Integer fromCore, Integer toCore, Integer fromThread, Integer toThread, String Soket, Integer fromSpeed, Integer toSpeed, Integer fromGen, Integer toGen, String brend){
        String query = 'Select Id, Name, Price__c From Processor__c Where ';
        String core = ' Number_of_cores__c >: fromCore And Number_of_cores__c <:toCore And ';
        String thread = ' Number_of_threads__c >:fromThread And Number_of_threads__c <:toThread And ';
        String speed = ' Clock_speed__c >: fromSpeed And Clock_speed__c <:toSpeed And ';
        String socket= ' Socket__c =: Soket And ';
        String generation = ' Generation__c >: fromGen And Generation__c <: toGen And ';
        String company = ' Company__c =: brend';
        return Database.query(query + core + thread + speed + socket + generation + company );
    }
    @AuraEnabled
    public static List<Motherboard__c> getMother(String Soket, Integer M2, Integer fromMMF, Integer toMMF, String Formfactor){
        String query = 'Select Id, Name, Price__c From Motherboard__c Where ';
        String socket = 'Socket__c =: Soket And ';
        String m = 'M2__c =: M2 And ';
        String mmf = 'Maximum_Memory_Frequency__c >:fromMMF And Maximum_Memory_Frequency__c <: toMMF And ';
        String form = 'Formfactor__c =: Formfactor';
        return Database.query(query + socket + m + mmf + form); //+ m 
    }
    @AuraEnabled
    public static List<Power_supply__c> getPower(Integer fromPower, Integer toPower, Integer fromNoise, Integer toNoise, Integer fromMaxCon, Integer toMaxCon, String Syst, String Formfactor){
        String query = 'Select Id, Name, Price__c From Power_supply__c Where ';
        String power = 'Power__c >: fromPower And Power__c <: toPower And ';
        String noise = 'Maximum_noise_level__c >:fromNoise And Maximum_noise_level__c <:toNoise And ';
        String conectors = 'Number_of_power_connectors__c >: fromMaxCon And Number_of_power_connectors__c <: toMaxCon And ';
        String type = 'Cooling_system__c =: Syst And ';
        String form = 'Formfactor__c =: Formfactor';
        return Database.query(query + power + noise + conectors + type + form);
    }
    @AuraEnabled
    public static List<HHD_Disk__c> getHHD(String Type, Integer fromCap, Integer toCap, Integer fromSpeed, Integer toSpeed, Integer fromBuf, Integer toBuf){
        String query = 'Select Id, Name, Price__c From HHD_Disk__c Where ';
        String typehhd = 'Type__c =: Type And ';
        String capacity = 'Storage_Capacity__c >: fromCap And Storage_Capacity__c <:toCap And ';
        String speed = 'Spindle_rotation_speed__c >: fromSpeed And Spindle_rotation_speed__c <: toSpeed And ';
        String buf = 'Buffer_capacity__c >: fromBuf And Buffer_capacity__c <: toBuf';
        return Database.query(query + typehhd + capacity + speed + buf);
    }
    @AuraEnabled
    public static List<SSD_Disk__c> getSSD(String Type, Integer fromCap, Integer toCap, String Formfactor, String Inter ){
        String query = 'Select Id, Name, Price__c From SSD_Disk__c Where ';
        String typessd = 'Type__c =: Type And ';
        String capacity = 'Capacity__c >: fromCap And Capacity__c <:toCap And ';
        String form = 'Formfactor__c =: Formfactor And ';
        String interf = 'Connection_interface__c =: Inter';
        return Database.query(query + typessd + capacity + form + interf);
    }
    @AuraEnabled
    public static List<RAM__c> getRAM(Integer fromCap, Integer toCap, Integer fromSlot, Integer toSlot, Integer fromFreq, Integer toFreq, String Type){
        String query = 'Select Id, Name, Price__c From RAM__c Where ';
        String capacity = 'Memory_capacity__c >: fromCap And Memory_capacity__c <:toCap And ';
        String slot = 'Number_of_slats__c >: fromSlot And Number_of_slats__c <: toSlot And ';
        String freq = 'Memory_Clock__c >: fromFreq And Memory_Clock__c <: toFreq And ';
        String typeram = 'Type_of_Memory__c =: Type';
        return Database.query(query + capacity + slot + freq  + typeram); 
    }
    @AuraEnabled
    public static List<Video_Card__c> getVideo(String Brend, String Con, String Inter, String Type, Integer fromCap, Integer toCap, Integer fromBit, Integer toBit){
        String query = 'Select Id, Name, Price__c From Video_Card__c Where ';
        String company = 'Company__c =: Brend And ';
        String conection = 'Connectors__c =: Con And ';
        String intervideo = 'Interface__c =:Inter And ';
        String typevideo = 'Type_of_Memory__c =: Type And ';
        String capacity = 'Memory_capacity__c >: fromCap And Memory_capacity__c <: toCap And ';
        String bit = 'Memory_bus_bit_depth__c >: fromBit And Memory_bus_bit_depth__c <: toBit';
        return Database.query(query + company + conection + intervideo + typevideo + capacity + bit);

    }
    @AuraEnabled
    public static List<Sound_Card__c> getSound(String Type, String Con, Integer fromChan, Integer toChan, String Color){
        String query = 'Select Id, Name, Price__c From Sound_Card__c Where ';
        String typesound = 'Type__c =: Type And ';
        String conn = 'Connection_interface__c =: Con And ';
        String channel = 'Channels__c >: fromChan And Channels__c <: toChan And ';
        String colorsound = 'Color__c =: Color';
        return Database.query(query + typesound + conn + channel + colorsound);
    }
    @AuraEnabled
    public static List<Corpus__c> getCorpus(String Type, Integer fromNumFans, Integer toNumFans, String Material){
        String query = 'Select Id, Name, Price__c From Corpus__c Where ';
        String typec = 'Type__c =: Type And ';
        String numFans = 'Number_of_installed_fans__c >: fromNumFans And Number_of_installed_fans__c <: toNumFans And ';
        String materialc = 'Material__c =: Material';
        return Database.query(query + typec + numFans + materialc);
    }
}